multipart:
  maxFileSize: 100MB
  maxRequestSize: 100MB
spring:
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
uocolle:
  watson:
    api-key: dummy
    collectionid: dummy